version: "3"

services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["python", "app.py"]

  redis:
    image: "redis:alpine"
